INSERT INTO MAJOR(NO) VALUES (1);

COMMIT;

INSERT INTO PROFESSOR(P_NO, MAJOR_NO) VALUES (1,1);

COMMIT;

INSERT INTO LECTURE(L_NO, L_UNIT, MAJOR_NO, PROFESSOR_P_NO) VALUES (123,3,1,1);
INSERT INTO LECTURE(L_NO, L_UNIT, MAJOR_NO, PROFESSOR_P_NO) VALUES (1234,3,1,1);
INSERT INTO LECTURE(L_NO, L_UNIT, MAJOR_NO, PROFESSOR_P_NO) VALUES (1235,3,1,1);
INSERT INTO LECTURE(L_NO, L_UNIT, MAJOR_NO, PROFESSOR_P_NO) VALUES (1236,3,1,1);
INSERT INTO LECTURE(L_NO, L_UNIT, MAJOR_NO, PROFESSOR_P_NO) VALUES (1237,3,1,1);
INSERT INTO LECTURE(L_NO, L_UNIT, MAJOR_NO, PROFESSOR_P_NO) VALUES (1238,3,1,1);
INSERT INTO LECTURE(L_NO, L_UNIT, MAJOR_NO, PROFESSOR_P_NO) VALUES (1239,3,1,1);
INSERT INTO LECTURE(L_NO, L_UNIT, MAJOR_NO, PROFESSOR_P_NO) VALUES (1230,3,1,1);
INSERT INTO LECTURE(L_NO, L_UNIT, MAJOR_NO, PROFESSOR_P_NO) VALUES (1231,3,1,1);
INSERT INTO LECTURE(L_NO, L_UNIT, MAJOR_NO, PROFESSOR_P_NO) VALUES (1232,3,1,1);

COMMIT;